version: '3.7'
services:
  es01:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kib01:
    image: kibana:7.8.0
    container_name: kibana
    ports:
      - 80:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: "http://es01:9200/"
#      ELASTICSEARCH_HOSTS: "http://es01:9200/"
      ELASTICSEARCH_REQUESTTIMEOUT: "300000"
      XPACK_SECURITY_ENABLED: "true"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "elasticpassword"
    network_mode: "host"
#    ports:
#      - '80:5601'
